services:
  adminer:
    networks:
      - default
    ports:
      - "8080:8080"
    labels: []

  backend:
    networks:
      - default
    ports:
      - "8000:8000"
    labels: []

  frontend:
    networks:
      - default
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VITE_API_URL=http://120.26.169.188:8000
        - NODE_ENV=production
    labels: []

networks:
  traefik-public:
    external: false
